apiVersion: apps/v1
kind: Deployment
metadata:
  name: udp-server-deployment
  labels:
    name: udp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: udp-server
  template:
    metadata:
      labels:
        name: udp-server
    spec:
      containers:
      - name: udp-server
        image: quay.io/rhn_support_hchaturv/udp-server
        imagePullPolicy: Always
        ports:
        - containerPort: 10001
          protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: udp-server-service
  labels:
    app: udp-server
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - port: 10001
    protocol: UDP
  selector:
    name: udp-server
